import hashlib
import os
import tempfile
from datetime import datetime

import streamlit as st
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
)


def calculate_hashes(file_path):
    md5 = hashlib.md5()
    sha1 = hashlib.sha1()
    sha256 = hashlib.sha256()

    with open(file_path, "rb") as file:
        while True:
            data = file.read(4096)

            if not data:
                break

            md5.update(data)
            sha1.update(data)
            sha256.update(data)

    return md5.hexdigest(), sha1.hexdigest(), sha256.hexdigest()


def create_pdf_report(
    case_id,
    evidence_id,
    examiner,
    description,
    file_name,
    file_size,
    created,
    modified,
    md5,
    sha1,
    sha256,
):
    report_file = tempfile.NamedTemporaryFile(
        delete=False,
        suffix=".pdf"
    )

    report_file.close()

    document = SimpleDocTemplate(
        report_file.name,
        pagesize=A4,
        rightMargin=20 * mm,
        leftMargin=20 * mm,
        topMargin=20 * mm,
        bottomMargin=20 * mm,
    )

    styles = getSampleStyleSheet()

    story = []

    story.append(
        Paragraph("FORENSIC ANALYSIS REPORT", styles["Title"])
    )
    story.append(Spacer(1, 10))

    story.append(
        Paragraph("Case Information", styles["Heading2"])
    )

    case_data = [
        ["Case ID", case_id],
        ["Evidence ID", evidence_id],
        ["Examiner", examiner],
        ["Description", description],
    ]

    case_table = Table(
        case_data,
        colWidths=[40 * mm, 120 * mm]
    )

    case_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.lightgrey,
                ),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )

    story.append(case_table)
    story.append(Spacer(1, 15))

    story.append(
        Paragraph("File Information", styles["Heading2"])
    )

    file_data = [
        ["File Name", file_name],
        ["File Size", f"{file_size} bytes"],
        ["Created", str(created)],
        ["Modified", str(modified)],
        [
            "Analysis Time",
            datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        ],
    ]

    file_table = Table(
        file_data,
        colWidths=[40 * mm, 120 * mm]
    )

    file_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                (
                    "BACKGROUND",
                    (0, 0),
                    (0, -1),
                    colors.lightgrey,
                ),
                ("FONTNAME", (0, 0), (0, -1), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )

    story.append(file_table)
    story.append(Spacer(1, 15))

    story.append(
        Paragraph("Cryptographic Hashes", styles["Heading2"])
    )

    hash_data = [
        ["Algorithm", "Hash Value"],
        ["MD5", md5],
        ["SHA-1", sha1],
        ["SHA-256", sha256],
    ]

    hash_table = Table(
        hash_data,
        colWidths=[40 * mm, 120 * mm]
    )

    hash_table.setStyle(
        TableStyle(
            [
                ("GRID", (0, 0), (-1, -1), 0.5, colors.black),
                (
                    "BACKGROUND",
                    (0, 0),
                    (-1, 0),
                    colors.lightgrey,
                ),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "TOP"),
            ]
        )
    )

    story.append(hash_table)
    story.append(Spacer(1, 20))

    story.append(
        Paragraph(
            "Report generated by Forensic File Analyzer.",
            styles["BodyText"],
        )
    )

    document.build(story)

    with open(report_file.name, "rb") as pdf:
        pdf_data = pdf.read()

    os.unlink(report_file.name)

    return pdf_data


st.set_page_config(
    page_title="Forensic File Analyzer",
    page_icon="🔬",
    layout="centered",
)

st.title("🔬 Forensic File Analyzer")
st.write(
    "Analyze digital evidence files and generate cryptographic hashes "
    "and forensic reports."
)

st.subheader("Case Information")

case_id = st.text_input("Case ID")
evidence_id = st.text_input("Evidence ID")
examiner = st.text_input("Examiner Name")
description = st.text_area("Evidence Description")

st.subheader("Evidence File")

uploaded_file = st.file_uploader(
    "Upload an evidence file",
    type=None,
)

if uploaded_file is not None:

    if st.button("Analyze Evidence"):

        with tempfile.NamedTemporaryFile(
            delete=False
        ) as temp_file:

            temp_file.write(uploaded_file.getbuffer())
            temp_path = temp_file.name

        try:
            file_info = os.stat(temp_path)

            created = datetime.fromtimestamp(
                file_info.st_ctime
            )

            modified = datetime.fromtimestamp(
                file_info.st_mtime
            )

            md5, sha1, sha256 = calculate_hashes(
                temp_path
            )

            st.success("Analysis completed successfully.")

            st.subheader("File Information")

            st.write("**File Name:**", uploaded_file.name)
            st.write("**File Size:**", file_info.st_size, "bytes")
            st.write("**Created:**", created)
            st.write("**Modified:**", modified)

            st.subheader("Cryptographic Hashes")

            st.code(f"MD5: {md5}")
            st.code(f"SHA-1: {sha1}")
            st.code(f"SHA-256: {sha256}")

            pdf_data = create_pdf_report(
                case_id,
                evidence_id,
                examiner,
                description,
                uploaded_file.name,
                file_info.st_size,
                created,
                modified,
                md5,
                sha1,
                sha256,
            )

            st.download_button(
                label="📄 Download Forensic PDF Report",
                data=pdf_data,
                file_name=f"{case_id}_{evidence_id}_forensic_report.pdf",
                mime="application/pdf",
            )

        finally:
            os.unlink(temp_path)